### ISSUE TITLE
error in wxporting as svg file

### ISSUE THREAD

**Issue by dumbdreamed** [excalidraw/excalidraw#5873]
hi, hope you are doing well, thanks for your efforts on this add-on and for keeping it updated.
my problem is that when I want to export my canvas as a SVG file the alignment of the lines and everything messes up.
this problem happens actually when i typed in Persian  and arabic language.
its the original one:
![image](https://user-images.githubusercontent.com/64626106/201536974-a0252999-0626-40bf-b8e1-9b83b057f962.png)
and the one below is the one that i exported as a svg file.
![image](https://user-images.githubusercontent.com/64626106/201536999-9f961353-002c-4d70-9b29-c35335fcc4e2.png)

**Comment by ad1992** [comment]
@dumbdreamed could you also export the drawing as a link if its not confidential ?
![image](https://user-images.githubusercontent.com/11256141/201611135-3e22f02f-22c6-4e4a-8763-69337a6eba5a.png)

**Comment by dumbdreamed** [comment]
yes of course but since i can't upload the file on the excalidraw site , I'll send you the mega link that upload them to it.
https://mega.nz/file/utBGzTZK#QNHhnc0Xwyo979wf-ZbQ0HJIM3iv9l40_vurW5vqJRM
hope it suffice.
and this is the link to the SVG file that I exported.
https://mega.nz/file/i0AwTTLB#gynTEYP-sy6zNcI7dUwf7sMiaZken_H0kp8MMHaMn24
and also there is another problem that I think is worth mentioning here and I don't know if I have to say it here or create another issue for it.
when I want to create a canvas in excalidraw mobile, it doesn't show the text properly on mobile but it looks good on the pc.
it looks good on the mobile if I double-tap on the text and keep it in the editing state.
to be specific the start and the end of a line lacks one or two letters.
![Screenshot_2022-11-14-20-16-58-199_md obsidian 1](https://user-images.githubusercontent.com/64626106/201719032-a1d5d1db-b043-4221-a31c-75eeb809b72f.jpg)
![Screenshot_2022-11-14-20-17-28-604_md obsidian](https://user-images.githubusercontent.com/64626106/201719062-a341a7d5-773b-4db0-8316-ccb939b2922e.jpg)
here are two picture showing two state and here is the excalidraw file that i took the screenshot from it.
https://mega.nz/file/q9hzma7Y#2kxggJ1HxDhe9qgvvLNk6AgaVMAcmnNkGHQ5eHOoV9A

**Comment by dwelle** [comment]
> @dwelle could this also be for same reason as #5866 ?

Partly, maybe — the parts with English text (using Virgil), and that part should now be fixed (https://github.com/excalidraw/excalidraw/pull/5878). Otherwise I don't think so.

**Comment by dumbdreamed** [comment]
> > @dwelle could this also be for same reason as #5866 ?
> 
> Partly, maybe — the parts with English text (using Virgil), and that part should now be fixed (#5878). Otherwise I don't think so.
> 
> But since this is in Obsidian, that fix will not be reflected until downstreaming the update to the fork. /cc @zsviczian
i don't think so,i changed the font but the problem still exists, and more on this everythig was good before the latest updates

**Comment by dwelle** [comment]
> i don't think so,i changed the font but the problem still exists, and more on this everythig was good before the latest updates

No idea what the latest updated in Obsidian was. Can you reproduce on https://excaliddaw.com?

**Comment by dumbdreamed** [comment]
> > i don't think so,i changed the font but the problem still exists, and more on this everythig was good before the latest updates
> 
> No idea what the latest updated in Obsidian was. Can you reproduce on https://excaliddaw.com?

unfortunately i cant import my excalidraw files on the website,because it gives me this error,
![image](https://user-images.githubusercontent.com/64626106/201956305-12addb2e-232d-4530-8feb-8fc1687bf1bf.png)

**Comment by Mrazator** [comment]
There have been a lot of changes to fonts and SVG export recently, is this still reproducible?
