### ISSUE TITLE
Multi-point arrows get skewed when resizing

### ISSUE THREAD

**Issue by pshihn** [excalidraw/excalidraw#661]
When resizing multi-point arrows, the transformations seem to be compounded rather than apply to the original state:
![Feb-01-2020 09-33-40](https://user-images.githubusercontent.com/833927/73596348-391b4500-44d6-11ea-885a-cd2a264e8c6f.gif)
Expected behavior:
![mpoint2](https://user-images.githubusercontent.com/833927/73596353-420c1680-44d6-11ea-99a1-8b7d73ea357f.gif)

**Comment by dwelle** [comment]
Known, and there's already a suggested strategy to be implemented: https://github.com/excalidraw/excalidraw/pull/338#issuecomment-579198383

Good to keep track of it, though!

**Comment by GasimGasimzada** [comment]
I am keeping track of it internally already :) Let's keep this issue open and I will reference it when I start my PR for it. I have some ideas on how it is going to work and I believe that resizing logic is going to get so much simpler for all elements; plus, no more shape regeneration :)

**Comment by dwelle** [comment]
We don't regenerate shape during resize already. Except, now that I look at it, we do for ellipses. But I'd swear we didn't (except when size change considerably). Is this a regression? /cc @pshihn

**Comment by pshihn** [comment]
For ellipses, roughjs ensures the *shape* of the ellipse doesn't change until the perimeter changes by a certain value. 
But, excalidraw does call roughjs on resize to generate the new coordinates every time. rough will keep the same shape/outline but coordinates will change.

You can scale the shape using canvas transforms and not call rough every time, but it will not work when the shape is filled with hachure/cross-hatch. The number of lines to fill the shape will be different at different size.

**Comment by GasimGasimzada** [comment]
@dwelle 
> We don't regenerate shape during resize already.

We set the shape to `null` in https://github.com/excalidraw/excalidraw/blob/master/src/index.tsx#L1400. Otherwise, changes will not be visible, right? Or do you mean something else that I am a bit confused about.

@pshihn 
> You can scale the shape using canvas transforms and not call rough every time, but it will not work when the shape is filled with hachure/cross-hatch. 

What will happen when we scale elements using canvas transforms? Will regenerating the shape fill hachure/cross-hatch lines? Or is it important to change width / height of a shape?

**Comment by pshihn** [comment]
When you tell rough to fill a square with 2x width and height, it will draw more hachure lines in the extra space. When just scaling, everything is 2x with the same number of hachure lines. 
Rough estimation:
![Asset 1](https://user-images.githubusercontent.com/833927/73597669-4be84680-44e3-11ea-8b58-23e66d0dda63.png)

**Comment by pshihn** [comment]
Note that if you're not filling the shape, scaling may be a faster operation - e.g. for arrows, outlines. Same for solid fills

**Comment by GasimGasimzada** [comment]
@pshihn It is good to know for hachures and cross-hatch because we can decrease number of shape generations based on the "scale factor." Until then, we can ignore regeneration if scale factor is between (0.5x - 2x the initial shape's size).

**Comment by dwelle** [comment]
I see. By regeneration I meant generating new shape altogether (so it looks different). Seed notwithstanding.

**Comment by lipis** [comment]
We just have to update the intermediate points according to the new ratio and redraw the arrow! Am I missing something here?

**Comment by pshihn** [comment]
@lipis I think @GasimGasimzada is trying to optimize resize for all shapes, not just arrows, that's why the digression.

**Comment by GasimGasimzada** [comment]
@dwelle aa that makes sense. I thought you were talking about our "caching" mechanism for shapes.

**Comment by GasimGasimzada** [comment]
@lipis Since I will be doing it for arrows / lines, I might as well at least try it out for shapes :)

**Comment by vjeux** [comment]
I'm not following the entire discussion. The way I believe resizing should work is the following:
- Update all the control points based on the resize ratio
- Drop the shape and redraw the whole arrow

The result would look as if the person moved all the control points by hand, which is likely what we want to happen.

It doesn't seem from the current behavior that it what is happening. We don't need to use canvas scale for this (and mimic what the video attached look like it's doing). For the rough issue, we use a constant seed so it shouldn't be an issue. If we don't want to use the same seed for each of the arrows in the path, we could derive a different seed for each of the paths based on the original one.

**Comment by dwelle** [comment]
@vjeux if we did that, we'd lose information when going to [0 width/height, or going to the negative](https://github.com/excalidraw/excalidraw/pull/338#issuecomment-579183325):

We want this behavior:

![excalidraw_multi_arrow_resizing_affinity](https://user-images.githubusercontent.com/5153846/73256539-61e3c780-41c2-11ea-9ee1-046d77895379.gif)

**Comment by vjeux** [comment]
Good point!

**Comment by GasimGasimzada** [comment]
I am currently working on it and setting up the scale for arrows. 

![Screen Recording 2020-02-04 at 3 11 26 PM](https://user-images.githubusercontent.com/807231/73740027-cc67ab00-4760-11ea-8466-618fda97904d.gif)

There are quite a number of edge cases here that still needs to be dealt with but this is how it is going to look like. My current strategy is to implement this to only arrows / lines by multiplying each point, then experiment with using context.scale, which will not require recreating the shape on every delta. Theoretically, it should increase performance during resizing because we will only regenerate shape when "scale" is 2x or 0.5s. If all goes well, then we can discuss applying the same transformation to other shapes.

I am still playing with it for now and testing to see if it is worth it and I will create a PR once I figure out some of the issues for it.

**Comment by vjeux** [comment]
This has been fixed!

**Comment by dwelle** [comment]
Not entirely → we still don't allow negative resize. I'll create a separate issue for it.
