### ISSUE TITLE
TypeError with App router using excalidraw

### ISSUE THREAD

**Issue by engelbrechtz** [excalidraw/excalidraw#7513]
I copied the code above, the app router gives me this error, how to solve this issue?

TypeError: _packages_excalidraw_node_modules_css_loader_dist_runtime_api_js__WEBPACK_IMPORTED_MODULE_1___default(...) is not a function

**Comment by MinhuaHuang** [comment]
me too

**Comment by ad1992** [comment]
Have you also added `useClient` in the file?
can you share a code sandbox reproducible example ?

**Comment by damien-schneider** [comment]
I can confirm the error, I have the same, even with "use client", and does the same when I don't import it dynamically.

PS : The error appears to me only if I use turbo.

**Comment by haydenbleasel** [comment]
You can circumvent this issue by adding `@excalidraw/excalidraw` to `transpilePackages` in your Next config :+1:

**Comment by haydenbleasel** [comment]
I get a similar error but it looks like it's trying to load scss files:

```
not-found-boundary.tsx:69 Uncaught 
TypeError: _packages_excalidraw_node_modules_css_loader_dist_runtime_api_js__WEBPACK_IMPORTED_MODULE_1___default(...) is not a function
    at eval (cjs.js??ruleSet[1].r….module.scss:12:134)
    at ./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./node_modules/sass-loader/dist/cjs.js!../../css/variables.module.scss (excalidraw.development.js:2027:1)
    at __webpack_require__ (excalidraw.development.js:5625:42)
    at eval (variables.module.scss:17:277)
    at ../../css/variables.module.scss (excalidraw.development.js:5249:1)
    at __webpack_require__ (excalidraw.development.js:5625:42)
    at eval (constants.ts:87:84)
    at ../../constants.ts (excalidraw.development.js:3687:1)
    at __webpack_require__ (excalidraw.development.js:5625:42)
    at eval (publicPath.js:2:68)
    at ./publicPath.js (excalidraw.development.js:4369:1)
    at __webpack_require__ (excalidraw.development.js:5625:42)
    at eval (entry.js:51:69)
    at ./entry.js (excalidraw.development.js:4347:1)
    at __webpack_require__ (excalidraw.development.js:5625:42)
    at excalidraw.development.js:5889:37
    at excalidraw.development.js:5892:11
    at webpackUniversalModuleDefinition (excalidraw.development.js:11:20)
    at Object.<anonymous> (excalidraw.development.js:18:2)
    at [project]/node_modules/.pnpm/@excalidraw+excalidraw@0.17.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js [app-client] (ecmascript) (http://…nt_157870.js:2519:3)
    at runtime-base.ts:347:21
    at runModuleExecutionHooks (runtime-base.ts:403:5)
    at instantiateModule (runtime-base.ts:345:5)
    at getOrInstantiateModuleFromParent (runtime-base.ts:451:10)
    at commonJsRequire (runtime-utils.ts:240:18)
    at Object.<anonymous> (main.js:10:17)
    at [project]/node_modules/.pnpm/@excalidraw+excalidraw@0.17.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@excalidraw/excalidraw/main.js [app-client] (ecmascript) (http://…main_586713.js:19:3)
    at runtime-base.ts:347:21
    at runModuleExecutionHooks (runtime-base.ts:403:5)
    at instantiateModule (runtime-base.ts:345:5)
    at getOrInstantiateModuleFromParent (runtime-base.ts:451:10)
    at esmImport (runtime-utils.ts:215:18)
    at 7e03c_@excalidraw_ex…ain_6757a0.js:12:16
    at async Excalidraw.loadableGenerated.modules [as loader] (index.tsx:14:23)
```

Figured it could be solved by adding `.scss` support to turbopack but no dice on that either:

```json
experimental: {
  turbo: {
      rules: {
        '*.scss': {
          loaders: ['style-loader', 'css-loader', 'sass-loader'],
          as: '*.js',
        },
      },
    },
}
```

**Comment by haydenbleasel** [comment]
Should be fixed with this PR and be part of an upcoming release.

https://github.com/vercel/turbo/pull/8848

**Comment by lagupa** [comment]
> Should be fixed with this PR and be part of an upcoming release.
> 
> [vercel/turborepo#8848](https://github.com/vercel/turborepo/pull/8848)

I have confirmed this did not fix the issue for me, it only works if turbo is not enabled. Next version: 14.2.11

**Comment by clement2026** [comment]
@lagupa The fix is not in the stable versions of excalidraw. You can try and pick an unstable version from https://www.npmjs.com/package/@excalidraw/excalidraw?activeTab=versions.

For example:

```json
  "dependencies": {
    "@excalidraw/excalidraw": "0.17.1-c1b310c",
  }
```

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/fb79ec2b-fd80-4ab1-8ced-305c523e24d6">

**Comment by andrewgosselin** [comment]
Yes! @clement2026's idea worked for me! ([ctx](https://github.com/excalidraw/excalidraw/issues/7513#issuecomment-2366149096))
I was having the same issue as @tswistak and downgrading to the latest unstable version worked (at the time of posting this `0.17.1-47ee8a0`). To make this work, I also had to install `lodash` because it seems they added that as a dependency in this version as it errors otherwise.
**I suppose we must wait until this is merged into stable?**

Also after doing this, I now get the following downloadable font errors:
![Image](https://github.com/user-attachments/assets/11615532-b7f3-400d-b43f-5e2fcc4ac65a)
I assume this may just be because I am on my local? However not sure and either way it is a bug with the way this gets integrated with NextJS as their official docs for the integration don't work at all properly out of the box.

**Comment by clement2026** [comment]
@andrewgosselin I’m glad to hear you found it helpful!

> **I suppose we must wait until this is merged into stable?**

Yeah, looks like it.

I also noticed the .woff2 errors in my NextJS project, but since they don’t affect anything, I’m fine with it.

**Comment by haroldSanchezb** [comment]
Hi, I tried theses versions and I getting this error

```bash
ERROR in ./node_modules/@excalidraw/excalidraw/dist/dev/index.js 1576:0-42
Module not found: Error: Can't resolve 'roughjs/bin/math' in '<my_path_app>/node_modules/@excalidraw/excalidraw/dist/dev'
Did you mean 'math.js'?
BREAKING CHANGE: The request 'roughjs/bin/math' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
```

Maybe the Package should build for cjs and esm, or change to type module in package.json, or If you know the solution, I appreciate (sorry my english its very bad)
