### ISSUE TITLE
Emojis rendered in the canvas are blurry on Firefox

### ISSUE THREAD

**Issue by sachintha-lk** [excalidraw/excalidraw#9470]
The emojis get blurred when rendered by the canvas in Firefox. I tested on Windows and Linux mint. The blur is **severe on Linux**, on Windows it is only a slight blur.

Chrome on both OSes renders the emojis without blur. 

|  | Linux screenshots |
|--------|--------|
| Firefox | ![Image](https://github.com/user-attachments/assets/2e119984-4f3d-4b84-af69-622c1be4c2e5) |
| Chrome | ![Image](https://github.com/user-attachments/assets/8724ef2d-9c55-4f12-b24e-3b8831b479bc)  | 

|  | Windows screenshots |
|--------|--------|
| Firefox | ![Image](https://github.com/user-attachments/assets/74b1da09-9b27-4b34-980f-c7224cec79da)|
| Chrome | ![Image](https://github.com/user-attachments/assets/fd0a12db-e7bf-42d6-8ba1-c7603e94b743) | 

This also affects the export as png. 
Exported with 3x scaling using Firefox on Linux.
![Image](https://github.com/user-attachments/assets/bc6733c7-dad0-4b14-bc73-a0bb2c630b56)

**Comment by dwelle** [comment]
Hi @sachintha-lk, can you check if it's fixed here? https://excalidraw-1jeddmuss-excalidraw.vercel.app/ 🙏

**Comment by sachintha-lk** [comment]
Hi @dwelle,  No looks like the issue is still present

https://github.com/user-attachments/assets/8c262804-1165-434c-a9c0-ca683f5273f1
